services:
  - type: web
    name: task-analyzer-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn task_analyzer.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: task_analyzer.settings
      - key: PYTHON_VERSION
        value: 3.12
